### ISSUE TITLE
Update Lambda runtime parameter of NodeJS

### ISSUE THREAD

**Issue by kaka-ruto** [cogini/multi-env-deploy#1]
The resource on the lambda edge module(`terraform/modules/lambda-edge/main.tf`) uses the `nodejs8.10` runtime parameter.

When executed, it throws the following error

`error creating Lambda function: InvalidParameterValueException: The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions`

Updating it to `nodejs12.x` works.

**Comment by draganavr** [comment]
Thanks @kaka-ruto.

Runtime version updated to nodejs12.x
