### ISSUE TITLE
Environment promotion?

### ISSUE THREAD

**Issue by karthikeayan** [cogini/multi-env-deploy#2]
How does the promotion to higher environments works?

**Comment by reachfh** [comment]
This example builds separate resources for each environment, e.g. AMIs. You can also share resources between environments with the proper permissions.

**Comment by karthikeayan** [comment]
Is there a approach for review process before promoting to higher environments?

**Comment by reachfh** [comment]
One approach is to use git branches and have separate CodePipeline configs for each environment pointing to the same repository. The staging environment builds from a staging tag and prod builds from a release tag.

If you want to use the exact same build artifact, then you can share the CodeDeploy release between environments. Or you can share an ECR container repository between environments. So you can tag a container as being latest and then deploy it to multiple environments.

**Comment by karthikeayan** [comment]
Sorry, I think the question needs more clarity.

I am not speaking about the application deployments. How do we promote the Terraform code itself to higher environments? For example, I create load balancer in Dev environment from Terraform, to deploy the same in QA and Staging, I don't want to copy paste bunch of files manually. Just like how we promote the application deployments, is there any suggested approach to promote the Terraform code itself?

**Comment by reachfh** [comment]
The normal approach is to copy files, assuming that the environments might be different. If you add a new app component, then you would set it up in dev first, creating the necessary components (ASG, S3 buckets, CodePipeline, etc). Then when you deploy it to QA, you would set up the same components.

If all your environments are very similar, then you can use ENV vars to run the same Terraform config in different locations. That's what this example does, to some extent, mostly focused on deploying the same production app to multiple geographies with the same config.

With Terragrunt, we are mainly copying the config files, the modules are shared between environments. Versioning them is a different problem, usually handled with git.
