### ISSUE TITLE
Invalid value for "default" parameter

### ISSUE THREAD

**Issue by dtbaker** [cogini/multi-env-deploy#4]
Hey! Just trying this out for a fresh app, so far so good except I'm getting caught up in `s3-app` and as this is my first dive into terraform I'm a little stuck at figuring out next steps.

```
cd s3-app/
terraform plan
``` 

produces these errors:

```
Error: Invalid function argument

  on main.tf line 70, in locals:
  70:       name = lookup(bucket, "name", "${local.bucket_prefix}-${replace(key, "_", "-")}")
    |----------------
    | local.bucket_prefix is "dtbaker-mycoolapp-dev-app"

Invalid value for "default" parameter: the default value must have the same
type as the map elements.

Error: Invalid function argument

  on main.tf line 75, in locals:
  75:       acl = lookup(bucket, "acl", "private")

Invalid value for "default" parameter: the default value must have the same
type as the map elements.
```

My attempted fix was to put the failing `name` and `acl` properties into the s3-app/terragrunt.hcl file like:

```
    assets = {
      encrypt = false
      cors = true
      acl = "private"
      name = "this-seems-to-work-assets"
    }
    # Config files
    config = {
      encrypt = true
      acl = "private"
      name = "this-seems-to-work-config"
    }
```

which seems to work, but I loose the dynamic variable for `name` and not sure how to bring it back.

Any ideas if there's a better fix I can apply in `main.tf` ?

Thanks!

**Comment by dtbaker** [comment]
using `get_env()` gets me unblocked again, will keep trucking with my first deploy thanks

```
    assets = {
      encrypt = false
      cors = true
      acl = "private"
      name = join("-", [get_env("ORG", ""), get_env("TF_VAR_app_name", ""), get_env("ENV", "dev"), "app", "assets"])
    }
    # Config files
    config = {
      encrypt = true
      acl = "private"
      name = join("-", [get_env("ORG", ""), get_env("TF_VAR_app_name", ""), get_env("ENV", "dev"), "app", "config"])
    }
```

**Comment by reachfh** [comment]
I guess you are using a newer version of Terraform, and it doesn't like something. 

We generally use asdf (https://asdf-vm.com/) to install the tools. If you do that, it will use the versions in the `.tool-versions` file.

**Comment by dtbaker** [comment]
```
$ asdf current

elixir         No version set for elixir; please run `asdf <global | local> elixir <version>`
erlang         No version set for erlang; please run `asdf <global | local> erlang <version>`
mariadb        10.5.7   (set by /home/dtbaker/.tool-versions)
nodejs         14.15.0  (set by /home/dtbaker/.tool-versions)
packer         1.6.0    (set by /home/dtbaker/blahblahblah/.tool-versions)
postgres       13.2     (set by /home/dtbaker/.tool-versions)
python         3.8.4    (set by /home/dtbaker/blahblahblah/.tool-versions)
ruby           No version set for ruby; please run `asdf <global | local> ruby <version>`
terraform      0.12.28  (set by /home/dtbaker/blahblahblah/.tool-versions)
terragrunt     0.23.29  (set by /home/dtbaker/blahblahblah/.tool-versions)
yarn           No version set for yarn; please run `asdf <global | local> yarn <version>`
```

yea :shrug: all good I seem to have got past that error, there's a few other weird ones as well do to with a `/dev/` path prefix it expected in the terraform s3 bucket: https://github.com/dtbaker/multi-env-deploy/compare/master...dtbaker:patch-1 

So I must be running something slightly off from your versions.

My first attempt was to bump those `.tool-versions` numbers to latest but that def blew up :joy:  

Cheers for the cool tool!!

**Comment by draganavr** [comment]
Hi @dtbaker 

Proper way to launch your infrastructure is by Terragrunt command, for example:

1. set working directory to terraform root directory i.e. multi-env-deploy/terraform
2. export ENV=dev
3. source ../set_env.sh
4. terragrunt plan --terragrunt-working-dir foo/$ENV/s3-app/

Hope this helps

**Comment by dtbaker** [comment]
Thanks @draganavr ! That makes much more sense. 

The `--terragrunt-working-dir "$ENV"` at the top of [building.md](https://github.com/cogini/multi-env-deploy/blob/master/terraform/building.md) wasn't working for me so I ended up running terragrunt in each app folder, which must be the cause of my issues. 

I'll try again with the full path like ` --terragrunt-working-dir foo/$ENV/s3-app/` and :crossed_fingers: that solves all the things.

Have a good day!!

**Comment by reachfh** [comment]
I generally just run terragrunt from the directories, e.g. `foo/$ENV/s3-app`. Then it's not necessary to specify the working dir.
